version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: tictactoe-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./web-service
    container_name: tictactoe-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./client
    container_name: tictactoe-frontend
    env_file:
      - .env
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
